#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Se necesitan exactamente dos parámetros"
else
    if [ $1 -gt $2 ]; then
        echo "$1 es mayor que $2"
    elif [ $1 -lt $2 ]; then
        echo "$2 es mayor que $1"
    else
        echo "Ambos números son iguales"
    fi
fi

