#!/bin/bash

if [ $# -lt 5 ]; then
    echo "Faltan parámetros"
elif [ $# -gt 5 ]; then
    echo "Sobran parámetros"
else
    for ((i = 1; i <= $#; i++)); do
        echo "El parámetro $i es ${!i}"
    done
fi

